const TARGET_NUMBER_CONSTRAINTS = {
	NUMBER_LENGTH: 3,
	RANGE_MIN: 1,
	RANGE_MAX: 9,
};

const COMMAND_OPTIONS = {
	RETRY: '1',
	END: '2',
};

const GAME_DIRECTION_INPUT_MESSAGE = {
	GUESS_NUMBER: '\n숫자를 입력해주세요 : ',
	RESTART_OR_END: `게임을 새로 시작하려면 ${COMMAND_OPTIONS.RETRY}, 종료하려면  ${COMMAND_OPTIONS.END}를 입력하세요.\n`,
};

const GAME_DIRECTION_OUTPUT_MESSAGE = {
	OPENING: '숫자 야구 게임을 시작합니다.',
	CORRECT_ANSWER: `\n${TARGET_NUMBER_CONSTRAINTS.NUMBER_LENGTH}개의 숫자를 모두 맞히셨습니다! 게임 종료`,
};

const RESULT_MESSAGE = {
	NOTHING: '낫싱',
	STRIKE: '스트라이크',
	BALL: '볼',
};

const ERROR_MESSAGE = {
	TYPE_CHECK: '숫자만 입력해주세요',
	LENGTH_CHECK: `${TARGET_NUMBER_CONSTRAINTS.NUMBER_LENGTH}자리 숫자를 입력해주세요`,
	DUPLICATE_CHECK: '중복된 숫자가 있습니다.',
	INPUT_CHECK: `${COMMAND_OPTIONS.RETRY}과 ${COMMAND_OPTIONS.END} 중 하나만 입력해주세요.`,
};

module.exports = {
	GAME_DIRECTION_INPUT_MESSAGE,
	GAME_DIRECTION_OUTPUT_MESSAGE,
	TARGET_NUMBER_CONSTRAINTS,
	RESULT_MESSAGE,
	ERROR_MESSAGE,
	COMMAND_OPTIONS,
};
